### ISSUE TITLE
Side drawer breaks

### ISSUE THREAD

**Issue by ruggedy** [ntrp/nativescript-ng2-drawer-seed#1]
TNS version : 2.1.1
device : OnePlus3
Android OS version : 6.0.1

Hi, Awesome project really, but when I tried implementing the class injection on my nativescript build, It threw an error 'extends' is undefined. 

Then I tried downloading and running your code on my device, but the menu button does not open the side drawer when i click it, and when I try swiping left, the app breaks and throws this error.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setVisibility(int)' on a null object reference
    at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.handleOnDown(RadSideDrawer.java:433)
    at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.onGesture(RadSideDrawer.java:413)
    at com.telerik.android.primitives.widget.sidedrawer.RadSideDrawer.onInterceptTouchEvent(RadSideDrawer.java:395)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2109)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2554)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2198)
    at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2432)
    at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1746)
    at android.app.Activity.dispatchTouchEvent(Activity.java:2824)
    at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2393)
    at android.view.View.dispatchPointerEvent(View.java:9557)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4263)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4102)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3789)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3846)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3697)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3663)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3671)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3644)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5955)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5929)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5890)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6058)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:323)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5507)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

do you know what might be the problem?

**Comment by ntrp** [comment]
I don't know at the moment, maybe 6.0.1 needs an upgrade of Telerik UI, I think I never tried running on that version. If I get a chance will try running it myself (I have updated my OS to 6.0.1 recently) but I am a bit busy in this period :(

**Comment by onofremartins** [comment]
Hi, i have the same problem. with android 6.0.1.
This template/seed is amazing to learning and delivery a quality app, i'm waiting this issue.

**Comment by rayehizoba** [comment]
Same here. I experienced the same issue. Great template btw. Waiting for a fix.

**Comment by ntrp** [comment]
I am sorry but at the moment I don't have much time to try and fix this. There is an attempt to port everything to angular 2.1.0 with the latest version nativescript runs at the moment but seems like the drawer has some problems at the moment.. I had problem on android 7.0.0, 6.0.1 and 5.1.1.

**Comment by ntrp** [comment]
Updated libraries and code to work with current drawer and tns tooling.
