### ISSUE TITLE
Crashes under Android emulator with `Error: read ECONNRESET`

### ISSUE THREAD

**Issue by KeithGillette** [ntrp/nativescript-ng2-drawer-seed#5]
I got the seed application built and launched in Android emulator under Windows 10 but it only runs for a short period and then the connection is reset and/or the emulator crashes (which doesn't happen with other NativeScript apps I have tested). Here is a sample console output:

```
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ws -->  {"msg":"connect","version":"1","support":["1","pre2","pre1"]}
JS: ws <--  {"server_id":"0"}
JS: ws <--  {"msg":"connected","session":"sGhxm7DfKo6xg2YZ8"}
JS: ws <--  {"msg":"added","collection":"todos","id":"8oPfhECD5w53SHPi8","fields":{"title":"Go buy groceries","description":"we need milk","done":true}}
JS: ws <--  {"msg":"added","collection":"todos","id":"5LXdoeRbrSMQtxJpM","fields":{"title":"Write to Alex","description":"ask about the meeting","done":true}}
JS: ws <--  {"msg":"added","collection":"todos","id":"CTJoPGqwpBgdoMoqf","fields":{"title":"Call Mom","description":"ask about the meeting","done":false}}
JS: ws <--  {"msg":"added","collection":"todos","id":"DefuTH3fxddaCqYMZ","fields":{"title":"Sweet","description":"","done":false}}
JS: ws <--  {"msg":"added","collection":"todos","id":"QLX9APPCDswAfSTHF","fields":{"title":"Hmmm.","description":"","done":false}}
JS: ws <--  {"msg":"added","collection":"todos","id":"DJjHJ5hosmXw4puMg","fields":{"title":"Uoaeuaoeu","description":"","done":false}}
JS: ws <--  {"msg":"ping"}
JS: ws -->  {"msg":"pong"}
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
```

**Comment by ntrp** [comment]
Could be an issue with the emulator, unfortunately I don´ t have any time to look into it.. On the device should work ok, also try Genymotion maybe it solves the problem.

**Comment by rdbhagat999** [comment]
I updated node to version 7.10.0, and npm to version 5.0.3. It worked for me.
